### ISSUE TITLE
[Epic] `async-profiler` support

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1456]
## Describe the feature
[`async-profiler`](https://github.com/async-profiler/async-profiler) is, well, a profiler for HotSpot JVMs. It's very powerful and it can output its data in the JFR binary file format, so it seems a natural fit that Cryostat should also be able to at least gather these files if a target JVM is determined to have `async-profiler` loaded as an agent. This would be somewhat similar to the support we currently have for the JMC bytecode instrumentation agent.

## Any other information?
https://github.com/async-profiler/async-profiler/discussions/496#discussioncomment-1614455

- [ ] Detect if `async-profiler` is present on target
- [ ] Readonly view for `async-profiler` data
- [ ] Dynamic updates for `async-profiler` state (ex. remote configuration)
