### ISSUE TITLE
[Meta] Drop release drafter action, add GitHub release notes config

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1825]
### Describe the feature

This release notes label config map should be copied to each project repository: https://github.com/cryostatio/cryostat-helm/blob/main/.github/release.yml . Or maybe there is a way to configure this at the org level?

The release drafter action: https://github.com/cryostatio/cryostat/blob/main/.github/release-drafter.yml should be dropped.

- [ ] cryostat
- [ ] cryostat3
- [x] cryostat-reports
- [x] jfr-datasource (doesn't use release drafter action, but should gain this new config map)
- [ ] cryostat-grafana-dashboard (doesn't use release drafter action, but should gain this new config map)
- [x] cryostat-agent
- [x] cryostat-helm (already done)
- [x] [cryostat-operator](https://github.com/cryostatio/cryostat-operator/pull/696)
- [x] cryostat-core
- [x] cryostat-web
