### ISSUE TITLE
[Epic] V4 API cleanup

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#550]
### Describe the feature

See also https://github.com/cryostatio/cryostat/issues/66 - these API/model improvements should also be included as a Step 0.

1. [x] (https://github.com/cryostatio/cryostat/issues/583) Remove API endpoints that simply redirect clients to newer API versioned endpoints. Redirects for other purposes will remain, ex. redirecting for file downloads
2. [x] (https://github.com/cryostatio/cryostat/issues/583)  Remove v2.x API response formatting and return to simpler JSON response structures everywhere applicable
3. [x] (https://github.com/cryostatio/cryostat/issues/583)  Rename remaining API endpoints to V4
4. [x] https://github.com/cryostatio/cryostat/issues/286
5. [x] [Update Agent to use V4 endpoints](https://github.com/cryostatio/cryostat-agent/pull/469)
6. [x] [Update web-client to use V4 endpoints](https://github.com/cryostatio/cryostat-web/pull/1331)
