### ISSUE TITLE
[Epic] Agent Plugin Integration

### ISSUE THREAD

**Issue by Josh-Matsuoka** [cryostatio/cryostat#576]
Goal: Integrate the JMC Agent Plugin functionality into cryostat. In particular we need to add backend support for communicating with the agent over JMX, as well as parsing and handling XML configurations supplied by the user. The backend will also need a set of HTTP handlers facilitating interaction between the frontend and the agent. The frontend will need to provide an interface for the user to upload probe templates and facilitate the addition and removal of probes to and from targets.

- [x] https://github.com/cryostatio/cryostat-core/issues/94
- [x] https://github.com/cryostatio/cryostat/issues/577
- [x] https://github.com/cryostatio/cryostat-web/issues/434

**Comment by andrewazores** [comment]
Closed by cryostatio/cryostat-web#558 , #1150, #1126
