### ISSUE TITLE
[Epic] Dashboard overview

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#945]
Currently the cryostat-web main Dashboard view is essentially empty, with nothing but a TargetSelect dropdown card and no actual information about that target displayed. The intent of the Dashboard view should be to provide some high-level information about the selected target(s), generally in a read-only manner but possibly with in-app links to other views that do allow modification actions. For example, there should not be a direct way to start a new Flight Recording on targets from the Dashboard view, but there might be a card that displays a condensed form of the Recordings view table, and that card might include a link to the full Recordings view.

Ideas for content to display on dashboard:
- [ ] Currently active recordings (only `RUNNING`?)
- [ ] Most recent archived recording(s)
- [ ] Total on-disk size of archived recordings from this target
- [ ] Automated Analysis Report information, but only orange/red scores
- [ ] Basic metrics (CPU, memory, network, I/O)
